"""empty message

Revision ID: d39459f53c94
Revises: 4248c892cafd
Create Date: 2019-06-11 21:21:56.790508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd39459f53c94'
down_revision = '4248c892cafd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'psex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('psex', mysql.ENUM('male', 'female'), nullable=True))
    # ### end Alembic commands ###
